# Housing Rental Analysis for San Francisco

In this challenge, your job is to use your data visualisation skills, including aggregation, interactive visualisations, and geospatial analysis, to find properties in the San Francisco market that are viable investment opportunities.

### Instructions

Use the `san_francisco_housing.ipynb` notebook to visualise and analyse the real-estate data.

Note that this assignment requires you to create a visualisation by using hvPlot and GeoViews. Additionally, you need to read the `sfo_neighborhoods_census_data.csv` file from the `Resources` folder into the notebook and create the DataFrame that you’ll use in the analysis.

The main task in this Challenge is to visualise and analyse the real-estate data in your Jupyter notebook. Use the `san_francisco_housing.ipynb` notebook to complete the following tasks:

* Calculate and plot the housing units per year.

* Calculate and plot the average prices per square foot.

* Compare the average prices by neighbourhood.

* Build an interactive neighbourhood map.

* Compose your data story.

#### Calculate and Plot the Housing Units per Year

For this part of the assignment, use numerical and visual aggregation to calculate the number of housing units per year, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

2. Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

3. Style and format the line plot to ensure a professionally styled visualisation.

4. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting bar chart.](Images/6-4-zoomed-housing-units-by-year.png)

5. Answer the following question:

    * What’s the overall trend in housing units over the period that you’re analysing?

#### Calculate and Plot the Average Sale Prices per Square Foot

For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Group the data by year, and then average the results. What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

2. Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

3. Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

    > **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting plot.](Images/6-4-avg-sale-px-sq-foot-gross-rent.png)

6. Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

    * Did any year experience a drop in the average sale price per square foot compared to the previous year?

    * If so, did the gross rent increase or decrease during that year?

#### Compare the Average Sale Prices by Neighbourhood

For this part of the assignment, use interactive visualisations and widgets to explore the average sale price per square foot by neighbourhood. To do so, complete the following steps:

1. Create a new DataFrame that groups the original DataFrame by year and neighbourhood. Aggregate the results by the `mean` of the groups.

2. Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

3. Create an interactive line plot with hvPlot that visualises both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighbourhood`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting plot.](Images/6-4-pricing-info-by-neighborhood.png)

6. Use the interactive visualisation to answer the following question:

    * For the Anza Vista neighbourhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012?

#### Build an Interactive Neighbourhood Map

For this part of the assignment, explore the geospatial relationships in the data by using interactive visualisations with hvPlot and GeoViews. To build your map, use the `sfo_data_df` DataFrame (created during the initial import), which includes the neighbourhood location data with the average prices. To do all this, complete the following steps:

1. Read the `neighbourhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighbourhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighbourhood”.

2. Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighbourhood_info_df` that groups the data by neighbourhood. Aggregate the results by the `mean` of the group.

3. Review the two code cells that concatenate the `neighbourhood_locations_df` DataFrame with the `all_neighbourhood_info_df` DataFrame. Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighbourhoods_df`. The second cell cleans the data and sets the “Neighbourhood” column. Be sure to run these cells to create the `all_neighbourhoods_df` DataFrame, which you’ll need to create the geospatial visualisation.

4. Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighbourhoods_df` DataFrame. Be sure to do the following:

    * Set the `size` parameter to “sale_price_sqr_foot”.

    * Set the `color` parameter to “gross_rent”.

    * Set the `frame_width` parameter to 700.

    * Set the `frame_height` parameter to 500.

    * Include a descriptive title.

    Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of a scatter plot created with hvPlot and GeoViews.](Images/6-4-geoviews-plot.png)

5. Use the interactive map to answer the following question:

    * Which neighbourhood has the highest gross rent, and which has the highest sale price per square foot?

#### Compose Your Data Story

Based on the visualisations that you created, answer the following questions:

* How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighbourhoods across San Francisco?

* What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighbourhoods exist that you would suggest for investment, and why?

In [1]:
# Import the required libraries and dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path
import warnings
import panel as pn
import holoviews as hv
warnings.filterwarnings('ignore')

## Import the data 

In [2]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighbourhoods_census_data.csv file from the Resources folder
csv_path = Path(r"C:\Users\ana_c\Documents\temp\assignment_5_due_oct_2_2023\real_estate\resources\sfo_neighbourhoods_census_data.csv")
sfo_data_df = pd.read_csv(csv_path, index_col ="year")
# Review the first five rows of the DataFrame
sfo_data_df.head()

neighbourhood  sale_price_sqr_foot  housing_units  gross_rent
year                                                                  
2010      Alamo Square           291.182945         372560        1239
2010        Anza Vista           267.932583         372560        1239
2010           Bayview           170.098665         372560        1239
2010  Buena Vista Park           347.394919         372560        1239
2010  Central Richmond           319.027623         372560        1239

In [3]:
# Review the last five rows of the DataFrame
sfo_data_df.tail()

neighbourhood  sale_price_sqr_foot  housing_units  gross_rent
year                                                                        
2016          Telegraph Hill           903.049771         384242        4390
2016              Twin Peaks           970.085470         384242        4390
2016  Van Ness/ Civic Center           552.602567         384242        4390
2016       Visitacion Valley           328.319007         384242        4390
2016           Westwood Park           631.195426         384242        4390

---

## Calculate and Plot the Housing Units per Year

For this part of the assignment, use numerical and visual aggregation to calculate the number of housing units per year, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

2. Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

3. Style and format the line plot to ensure a professionally styled visualisation.

4. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting bar chart.](Images/6-4-zoomed-housing-units-by-year.png)

5. Answer the following question:

    * What’s the overall trend in housing units over the period that you’re analysing?

### Step 1: Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

In [4]:
#Use the groupby function to group the data by year. 
#Aggregating the results by the mean of the groups.

housing_units_by_year = sfo_data_df.groupby('year').mean()

# Review the DataFrame
housing_units_by_year

sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

In [5]:
# Grouping by year and averaging the results.
housing_units_by_year = sfo_data_df.groupby("year").housing_units.mean()

# Review the DataFrame
housing_units_by_year

year
2010    372560.0
2011    374507.0
2012    376454.0
2013    378401.0
2014    380348.0
2015    382295.0
2016    384242.0
Name: housing_units, dtype: float64

### Step 2: Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

### Step 3: Style and format the line plot to ensure a professionally styled visualisation.

In [6]:
# Create a visual aggregation explore the housing units by year
housing_units_by_year.hvplot.bar(
    x='year', 
    y='housing_units',
    rot=90,
    xlabel='Year', 
    ylabel='Housing Units'
).opts(
    yformatter='%.0f'
)

:Bars   [year]   (housing_units)

### Step 5: Answer the following question:

**Question:** What is the overall trend in housing_units over the period being analysed?

**Answer:** The overall trend shows annual increase of the housing units available.

---

## Calculate and Plot the Average Sale Prices per Square Foot

For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Group the data by year, and then average the results. What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

2. Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

3. Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

    > **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting plot.](Images/6-4-avg-sale-px-sq-foot-gross-rent.png)

6. Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

    * Did any year experience a drop in the average sale price per square foot compared to the previous year?

    * If so, did the gross rent increase or decrease during that year?

### Step 1: Group the data by year, and then average the results.

In [7]:
#Use the groupby function to group the data by year. 
#Aggregating the results by the mean of the groups.

housing_units_by_year = sfo_data_df.groupby('year')[["sale_price_sqr_foot", "gross_rent"]].mean()

# Review the DataFrame
housing_units_by_year

sale_price_sqr_foot  gross_rent
year                                 
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

**Question:** What is the lowest gross rent reported for the years included in the DataFrame?

**Answer:** # The lowest gross rent reported was $1239 in the year 2010

### Step 2: Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

In [8]:
#filtering out the housing_units column
housing_units_by_year = sfo_data_df.groupby('year')[["sale_price_sqr_foot", "gross_rent"]].mean()

# Review the DataFrame
housing_units_by_year

sale_price_sqr_foot  gross_rent
year                                 
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

### Step 3: Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

> **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`

### Step 4: Style and format the line plot to ensure a professionally styled visualisation.


In [9]:
# Plot prices_square_foot_by_year. 
housing_units_by_year.hvplot.line(legend = True)

:NdOverlay   [Variable]
   :Curve   [year]   (value)

In [10]:
# Include labels for the x- and y-axes, and a title.
housing_units_by_year.hvplot.line(xlabel='Year', ylabel='Gross Rent/Square Price per Square Foot', title="Sale Price per Square Foot and Average Gross Rent 2010-2016 - San Francisco", legend = True)

:NdOverlay   [Variable]
   :Curve   [year]   (value)

### Step 6: Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

**Question:** Did any year experience a drop in the average sale price per square foot compared to the previous year?

**Answer:** The average sale price per square foot decreased YoY in 2011 by approximately of 28 dollars, from 369 to 341 dollars. 

**Question:** If so, did the gross rent increase or decrease during that year?

**Answer:** In 2011, the rent increased by 291 dollars. Going from 1,239 in 2010 to 1,530 dollars. 

---

## Compare the Average Sale Prices by Neighbourhood

For this part of the assignment, use interactive visualisations and widgets to explore the average sale price per square foot by neighbourhood. To do so, complete the following steps:

1. Create a new DataFrame that groups the original DataFrame by year and neighbourhood. Aggregate the results by the `mean` of the groups.

2. Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

3. Create an interactive line plot with hvPlot that visualises both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighbourhood`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting plot.](Images/6-4-pricing-info-by-neighborhood.png)

6. Use the interactive visualisation to answer the following question:

    * For the Anza Vista neighbourhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012?


### Step 1: Create a new DataFrame that groups the original DataFrame by year and neighbourhood. Aggregate the results by the `mean` of the groups.

In [11]:
# Read the file again
csv_path = Path(r"C:\Users\ana_c\Documents\temp\assignment_5_due_oct_2_2023\real_estate\resources\sfo_neighbourhoods_census_data.csv")
sfo_data_df = pd.read_csv(csv_path, index_col ="year")

# Review the first five rows of the DataFrame
sfo_data_df.head(5)

neighbourhood  sale_price_sqr_foot  housing_units  gross_rent
year                                                                  
2010      Alamo Square           291.182945         372560        1239
2010        Anza Vista           267.932583         372560        1239
2010           Bayview           170.098665         372560        1239
2010  Buena Vista Park           347.394919         372560        1239
2010  Central Richmond           319.027623         372560        1239

In [12]:
# Review the last five rows of the DataFrame
sfo_data_df.tail(5)

neighbourhood  sale_price_sqr_foot  housing_units  gross_rent
year                                                                        
2016          Telegraph Hill           903.049771         384242        4390
2016              Twin Peaks           970.085470         384242        4390
2016  Van Ness/ Civic Center           552.602567         384242        4390
2016       Visitacion Valley           328.319007         384242        4390
2016           Westwood Park           631.195426         384242        4390

### Step 2: Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

In [13]:
# Group by year and neighbourhood and then create a new dataframe of the mean values
# Create an empty dataframe to store the aggregated results
result_df = pd.DataFrame(columns=['year','neighbourhood','sale_price_sqr_foot','gross_rent'])

# define a chunk size of number of rows to process at a time
chunk_size = 200

# read the csv file by chunks
csv_reader = pd.read_csv(csv_path, chunksize = chunk_size)

# iterate over the chunks and perform grouping and aggregations
for chunk in csv_reader:
    grouped = chunk.groupby(['year','neighbourhood', 'sale_price_sqr_foot'])['gross_rent'].mean().reset_index()
    result_df = result_df.append(grouped, ignore_index=True)
    
result_df.head()
#result_df.head(60)

year     neighbourhood  sale_price_sqr_foot  gross_rent
0  2010      Alamo Square           291.182945      1239.0
1  2010        Anza Vista           267.932583      1239.0
2  2010           Bayview           170.098665      1239.0
3  2010  Buena Vista Park           347.394919      1239.0
4  2010  Central Richmond           319.027623      1239.0

### Step 3: Create an interactive line plot with hvPlot that visualises both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighbourhood`.

In [14]:
# create a list of unique neighbourhoods
neighbourhoods = result_df['neighbourhood'].unique()
neighbourhoods

array(['Alamo Square', 'Anza Vista', 'Bayview', 'Buena Vista Park',
       'Central Richmond', 'Central Sunset', 'Corona Heights',
       'Cow Hollow', 'Croker Amazon', 'Diamond Heights', 'Downtown ',
       'Eureka Valley/Dolores Heights', 'Excelsior',
       'Financial District North', 'Financial District South',
       'Forest Knolls', 'Glen Park', 'Golden Gate Heights',
       'Haight Ashbury', 'Hayes Valley', 'Hunters Point', 'Ingleside ',
       'Inner Mission', 'Inner Parkside', 'Inner Richmond',
       'Inner Sunset', 'Jordan Park/Laurel Heights',
       'Lake --The Presidio', 'Lone Mountain', 'Lower Pacific Heights',
       'Marina', 'Miraloma Park', 'Mission Bay', 'Mission Dolores',
       'Mission Terrace', 'Nob Hill', 'Noe Valley', 'Oceanview',
       'Outer Parkside', 'Outer Richmond ', 'Outer Sunset',
       'Pacific Heights', 'Park North', 'Parkside',
       'Parnassus/Ashbury Heights', 'Portola', 'Potrero Hill',
       'Presidio Heights', 'Russian Hill', 'South Beach',


In [15]:
#create a dropdown widget for neighbourhoods
#neighbourhood_dropdown

neighbourhood_dropdown = pn.widgets.Select(name="Select Neighbourhood", options=list(result_df['neighbourhood'].unique()))

# show the dropdown
neighbourhood_dropdown


Select(options=['Alamo Square', ...], value='Alamo Square')

In [16]:
housing_units_by_year = sfo_data_df.groupby('year')[["sale_price_sqr_foot", "gross_rent"]].mean()
grouped = chunk.groupby(['year','neighbourhood', 'sale_price_sqr_foot'])['gross_rent'].mean().reset_index()


In [17]:
# create a function to update the plot based on the selected neighbourhood
def update_plot(selected_neighbourhood):
    selected_data = result_df[result_df['neighbourhood'] == selected_neighbourhood]
    line_plot = selected_data.hvplot.line(x='year', y=["sale_price_sqr_foot", "gross_rent"], xlabel='Year', ylabel='Gross Rent/Sale Price per Square Foot',
    title=f'Sale Price Per Square Foot and Average Gross Rent for {selected_neighbourhood}', legend=True)
    
    return line_plot

In [18]:
# create an interactive widget with the dropdown menu
widget = pn.interact(update_plot, selected_neighbourhood=neighbourhood_dropdown) 

### Step 4: Style and format the line plot to ensure a professionally styled visualisation.

In [19]:
# Use hvplot to create an interactive line plot of the average price per square foot
# The plot should have a dropdown selector for the neighbourhood
# show the interactive widget
widget.servable()

Column(sizing_mode='fixed')
    [0] Column
        [0] Select(options=['Alamo Square', ...], value='Alamo Square')
    [1] Row(sizing_mode='fixed')
        [0] HoloViews(NdOverlay, height=300, name='interactive01292', sizing_mode='fixed', width=700)

### Step 6: Use the interactive visualisation to answer the following question:

**Question:** For the Anza Vista neighbourhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 

**Answer:** For the Anza Vista neighbourhood, the average sale price per square foot for 2016 is LESS (88.402 dollars) than the price that’s listed for 2012 (344.491 dollars). 

---

## Build an Interactive Neighbourhood Map

For this part of the assignment, explore the geospatial relationships in the data by using interactive visualisations with hvPlot and GeoViews. To build your map, use the `sfo_data_df` DataFrame (created during the initial import), which includes the neighbourhood location data with the average prices. To do all this, complete the following steps:

1. Read the `neighbourhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighbourhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighbourhood”.

2. Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighbourhood_info_df` that groups the data by neighbourhood. Aggregate the results by the `mean` of the group.

3. Review the two code cells that concatenate the `neighbourhood_locations_df` DataFrame with the `all_neighbourhood_info_df` DataFrame. Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighbourhoods_df`. The second cell cleans the data and sets the “Neighbourhood” column. Be sure to run these cells to create the `all_neighbourhoods_df` DataFrame, which you’ll need to create the geospatial visualisation.

4. Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighbourhoods_df` DataFrame. Be sure to do the following:

    * Set the `size` parameter to “sale_price_sqr_foot”.

    * Set the `color` parameter to “gross_rent”.

    * Set the `frame_width` parameter to 700.

    * Set the `frame_height` parameter to 500.

    * Include a descriptive title.

    Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of a scatter plot created with hvPlot and GeoViews.](Images/6-4-geoviews-plot.png)

5. Use the interactive map to answer the following question:

    * Which neighbourhood has the highest gross rent, and which has the highest sale price per square foot?

### Step 1: Read the `neighbourhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighbourhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighbourhood”.

In [20]:
# Read the csv file
csv_path = Path(r"C:\Users\ana_c\Documents\temp\assignment_5_due_oct_2_2023\real_estate\resources\neighbourhoods_coordinates.csv")
  
# Load neighbourhoods coordinates data
neighbourhood_locations_df = pd.read_csv(csv_path)
 
# Review the DataFrame
neighbourhood_locations_df

Neighbourhood        Lat         Lon
0         Alamo Square  37.791012 -122.402100
1           Anza Vista  37.779598 -122.443451
2              Bayview  37.734670 -122.401060
3      Bayview Heights  37.728740 -122.410980
4       Bernal Heights  37.728630 -122.443050
..                 ...        ...         ...
68         West Portal  37.740260 -122.463880
69    Western Addition  37.792980 -122.435790
70  Westwood Highlands  37.734700 -122.456854
71       Westwood Park  37.734150 -122.457000
72         Yerba Buena  37.792980 -122.396360

[73 rows x 3 columns]

### Step 2: Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighbourhood_info_df` that groups the data by neighbourhood. Aggregate the results by the `mean` of the group.

In [21]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighbourhoods_census_data.csv file from the Resources folder
csv_path = Path(r"C:\Users\ana_c\Documents\temp\assignment_5_due_oct_2_2023\real_estate\resources\sfo_neighbourhoods_census_data.csv")
sfo_data_df = pd.read_csv(csv_path, index_col ="year")
# Review the first five rows of the DataFrame
sfo_data_df.head()

neighbourhood  sale_price_sqr_foot  housing_units  gross_rent
year                                                                  
2010      Alamo Square           291.182945         372560        1239
2010        Anza Vista           267.932583         372560        1239
2010           Bayview           170.098665         372560        1239
2010  Buena Vista Park           347.394919         372560        1239
2010  Central Richmond           319.027623         372560        1239

In [28]:
# Group by year and neighbourhood and then create a new dataframe of the mean values
# Create an empty dataframe to store the aggregated results
all_neighbourhood_info_df = pd.DataFrame(columns=['year','neighbourhood','sale_price_sqr_foot','gross_rent'])

# define a chunk size of number of rows to process at a time
chunk_size = 200

# read the csv file by chunks
csv_reader = pd.read_csv(csv_path, chunksize = chunk_size, index_col ="year")

# iterate over the chunks and perform grouping and aggregations
for chunk in csv_reader:
    grouped = chunk.groupby(['year','neighbourhood', 'sale_price_sqr_foot'])['gross_rent'].mean().reset_index()
    all_neighbourhood_info_df = result_df.append(grouped, ignore_index=True)
    
all_neighbourhood_info_df.head()
#result_df.head(60)


year     neighbourhood  sale_price_sqr_foot  gross_rent
0  2010      Alamo Square           291.182945      1239.0
1  2010        Anza Vista           267.932583      1239.0
2  2010           Bayview           170.098665      1239.0
3  2010  Buena Vista Park           347.394919      1239.0
4  2010  Central Richmond           319.027623      1239.0

### Step 3: Review the two code cells that concatenate the `neighbourhood_locations_df` DataFrame with the `all_neighbourhood_info_df` DataFrame. 

Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighbourhoods_df`. 

The second cell cleans the data and sets the “Neighbourhood” column. 

Be sure to run these cells to create the `all_neighbourhoods_df` DataFrame, which you’ll need to create the geospatial visualisation.

In [29]:
# Using the Pandas `concat` function, join the 
# neighbourhood_locations_df and the all_neighbourhood_info_df DataFrame
# The axis of the concatenation is "columns".
# The concat function will automatially combine columns with
# identical information, while keeping the additional columns.
all_neighbourhoods_df = pd.concat(
    [neighbourhood_locations_df, all_neighbourhood_info_df], 
    axis="columns",
    sort=False
)

# Review the resulting DataFrame
display(all_neighbourhoods_df.head())
display(all_neighbourhoods_df.tail())


Neighbourhood        Lat         Lon  year     neighbourhood  \
0     Alamo Square  37.791012 -122.402100  2010      Alamo Square   
1       Anza Vista  37.779598 -122.443451  2010        Anza Vista   
2          Bayview  37.734670 -122.401060  2010           Bayview   
3  Bayview Heights  37.728740 -122.410980  2010  Buena Vista Park   
4   Bernal Heights  37.728630 -122.443050  2010  Central Richmond   

   sale_price_sqr_foot  gross_rent  
0           291.182945      1239.0  
1           267.932583      1239.0  
2           170.098665      1239.0  
3           347.394919      1239.0  
4           319.027623      1239.0

Neighbourhood  Lat  Lon  year           neighbourhood  \
579           NaN  NaN  NaN  2016          Telegraph Hill   
580           NaN  NaN  NaN  2016              Twin Peaks   
581           NaN  NaN  NaN  2016  Van Ness/ Civic Center   
582           NaN  NaN  NaN  2016       Visitacion Valley   
583           NaN  NaN  NaN  2016           Westwood Park   

     sale_price_sqr_foot  gross_rent  
579           903.049771      4390.0  
580           970.085470      4390.0  
581           552.602567      4390.0  
582           328.319007      4390.0  
583           631.195426      4390.0

In [30]:
# Call the dropna function to remove any neighbourhoods that do not have data
all_neighbourhoods_df = all_neighbourhoods_df.reset_index().dropna()

# Rename the "index" column as "Neighbourhood" for use in the Visualisation
all_neighbourhoods_df = all_neighbourhoods_df.rename(columns={"index": "Neighbourhood"})

# Review the resulting DataFrame
display(all_neighbourhoods_df.head())
display(all_neighbourhoods_df.tail())

Neighbourhood    Neighbourhood        Lat         Lon  year  \
0             0     Alamo Square  37.791012 -122.402100  2010   
1             1       Anza Vista  37.779598 -122.443451  2010   
2             2          Bayview  37.734670 -122.401060  2010   
3             3  Bayview Heights  37.728740 -122.410980  2010   
4             4   Bernal Heights  37.728630 -122.443050  2010   

      neighbourhood  sale_price_sqr_foot  gross_rent  
0      Alamo Square           291.182945      1239.0  
1        Anza Vista           267.932583      1239.0  
2           Bayview           170.098665      1239.0  
3  Buena Vista Park           347.394919      1239.0  
4  Central Richmond           319.027623      1239.0

Neighbourhood       Neighbourhood       Lat         Lon  year  \
68            68         West Portal  37.74026 -122.463880  2011   
69            69    Western Addition  37.79298 -122.435790  2011   
70            70  Westwood Highlands  37.73470 -122.456854  2011   
71            71       Westwood Park  37.73415 -122.457000  2011   
72            72         Yerba Buena  37.79298 -122.396360  2011   

                    neighbourhood  sale_price_sqr_foot  gross_rent  
68                  Croker Amazon           145.853380      1530.0  
69                Diamond Heights           382.352261      1530.0  
70                      Downtown            234.281624      1530.0  
71                Duboce Triangle           295.779378      1530.0  
72  Eureka Valley/Dolores Heights           413.162804      1530.0

### Step 4: Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighbourhoods_df` DataFrame. Be sure to do the following:

* Set the `geo` parameter to True.
* Set the `size` parameter to “sale_price_sqr_foot”.
* Set the `color` parameter to “gross_rent”.
* Set the `frame_width` parameter to 700.
* Set the `frame_height` parameter to 500.
* Include a descriptive title.

In [40]:
# Create a plot to analyse neighbourhood info
# YOUR CODE HERE
all_neighbourhoods_df.hvplot.points(
    'Longitude', 
    'Latitude', 
    geo=True, 
    size = "ssale_price_sqr_foot",
    color='gross_rent',
    #tiles='OSM',
    frame_width = 700,
    frame_height = 500,
    title = 'pl')

# Show the plot
all_neighbourhoods_df

DataError: Dimensions may not reference duplicated DataFrame columns (found duplicate 'Neighbourhood' columns). If you want to plot a column against itself simply declare two dimensions with the same name. 

PandasInterface expects tabular data, for more information on supported datatypes see http://holoviews.org/user_guide/Tabular_Datasets.html

### Step 5: Use the interactive map to answer the following question:

**Question:** Which neighbourhood has the highest gross rent, and which has the highest sale price per square foot?

**Answer:** # YOUR ANSWER HERE

## Compose Your Data Story

Based on the visualisations that you created, answer the following questions:

**Question:**  How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighbourhoods across San Francisco?

**Answer:** # YOUR ANSWER HERE

**Question:** What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighbourhoods exist that you would suggest for investment, and why?

**Answer:** # YOUR ANSWER HERE